use_frameworks!

target 'TaskRunner_Example' do
    pod 'TaskRunner', :path => '../'

    target 'Tests' do
        inherit! :search_paths

        pod 'Quick', '~> 0.10'
        pod 'Nimble', '~> 5.0.0'
    end
end
