platform :ios, '9.3'
use_frameworks!

target 'TaskRunner_Example' do
    pod 'TaskRunner', :path => '../'

    target 'Tests' do
        inherit! :search_paths

        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.3'
    end
end
