# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
xcode_workspace: Example/TaskRunner.xcworkspace
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
xcode_scheme: TaskRunner-Example
cache: cocoapods
podfile: Example/Podfile
before_install:
#- sudo gem install cocoapods 1.4.0
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild test -workspace Example/TaskRunner.xcworkspace -scheme TaskRunner-Example -sdk iphonesimulator11.2 -destination '' ONLY_ACTIVE_ARCH=NO | xcpretty

#- pod lib lint
#- xcodebuild build-for-testing test-without-building -scheme TaskRunner-Example -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
#- xcodebuild build-for-testing test-without-building -scheme TaskRunner-Example -configuration Release -sdk iphonesimulator -destination "name=iPhone 7" ENABLE_TESTABILITY=YES | xcpretty -c
#- xcodebuild clean test -workspace Example/TaskRunner.xcworkspace -scheme TaskRunner-Example -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet