# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
xcode_workspace: Example/TaskRunner.xcworkspace
xcode_scheme: TaskRunner-Example
cache: cocoapods
podfile: Example/Podfile
branches:
  only:
    - master
before_install:
  - gem install cocoapods:1.1.0
  - pod install --project-directory=Example
  - gem install xcpretty -N
install: echo "<3"
script:
- set -o pipefail
- xcodebuild test -workspace Example/TaskRunner.xcworkspace -scheme TaskRunner-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty -c