# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
xcode_workspace: Example/TaskRunner.xcworkspace
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
xcode_scheme: TaskRunner-Example
cache: cocoapods
podfile: Example/Podfile
before_install:
- sudo security delete-certificate -Z 0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75 /Library/Keychains/System.keychain
- sudo gem install cocoapods 1.4.0
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild build-for-testing test-without-building -scheme TaskRunner-Example -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
- xcodebuild build-for-testing test-without-building -scheme TaskRunner-Example -configuration Release -sdk iphonesimulator -destination "name=iPhone 7" ENABLE_TESTABILITY=YES | xcpretty -c

#- pod lib lint
#- xcodebuild test -workspace Example/TaskRunner.xcworkspace -scheme TaskRunner-Example -sdk iphonesimulator10.3 -destination '' ONLY_ACTIVE_ARCH=NO | xcpretty
#- xcodebuild clean test -workspace Example/TaskRunner.xcworkspace -scheme TaskRunner-Example -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet